### PR TITLE
homework from stream

### PR DESCRIPTION
**Pull request by polybiusproxy**
there u go master
now gimme an A+

### CODE REVIEW

**Comment by polybiusproxy** [comment]
didnt added sound cuz im lazy lol

**Comment by ninjamuffin99** [comment]
looks pretty good, maybe make it COUNT the amount of rings you've collected, and even display it on screen ;)

**Comment by polybiusproxy** [comment]
> looks pretty good, maybe make it COUNT the amount of rings you've collected, and even display it on screen ;)

sure! i was planning to do that but i thought making just what the homework says would be better

**Comment by polybiusproxy** [comment]
done! check it pls lol

**Comment by leafiamusic** [comment]
great job *claps*

**Comment by polybiusproxy** [comment]
> great job _claps_

thx lol

**Pull request closed without merging**
